# Permalinks
permalink:           pretty

# Setup
title:               nickbona.com
tagline:             Software Developer & Technologist
url:                 https://nbonatsakis.github.io
paginate:            1
baseurl:             ""

# About/contact
author:
  name:              Nick Bonatsakis
  url:               https://nbonatsakis.github.io
  email:             nbonatsakis@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/nbonatsakis/nbonatsakis.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

pages_list:       
  Blog: 'https://medium.com/nickbona'
  Experience: '/experience.html'
  Portfolio: '/portfolio.html'
  Contact: '/contact.html'
